FROM node:12-alpine

USER root
RUN apk add --no-cache --virtual .build-deps git make
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Install app dependencies
COPY package.json ./
RUN npm install --loglevel warn

# Bundle app source
COPY . ./

RUN mkdir -p ./dist/webfonts \
  && cp -R node_modules/@fortawesome/fontawesome-free/webfonts ./dist/

RUN chown node:node /home/node -R \
  && chmod -R 750 /home/node/app

USER node
EXPOSE 3000
CMD ["npm", "run", "dev"]
