version: '3.4'
services:
  api:
    build:
      context: .
      target: builder-client
    ports:
     - "3001:3001"
    volumes:
     - ./src:/home/node/app/src
     - ./bin:/home/node/app/bin
    tty: true
    environment:
      HOSTNAME: "localhost:3001"
      NODE_ENV: "development"
      PORT: 3001
    command: ["npm","run","dev-api"]
  web:
    build:
      context: .
      target: builder-client
    ports:
     - "3000:3000"
    volumes:
     - ./src:/home/node/app/src
     - ./bin:/home/node/app/bin
     - ./test:/home/node/app/test
     - ./assets:/home/node/app/assets
     - ./dist:/home/node/app/dist
     - ./webpack.config.js:/home/node/app/webpack.config.js
     - ./.babelrc.json:/home/node/app/.babelrc.json
    tty: true
    environment:
      HOSTNAME: "localhost:3000"
      NODE_ENV: "development"
    command: ["npm","run","dev-web"]
