version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-dev
    tty: true
    environment:
      HOSTNAME: "localhost:3000"
      NODE_ENV: "development"
    command: ["npm","run","test"]
